# ============================================================================
# CORTEX MEMORY MCP - QDRANT VECTOR DATABASE AUTO-START CONFIGURATION
# ============================================================================
# CRITICAL DATABASE FOR MEMORY SYSTEM - HIGH AVAILABILITY CONFIGURATION
# - Auto-restart policy: always (max availability)
# - Health checks included
# - Persistent data storage
# - Network isolation for security

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: cortex-qdrant
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__LOG_LEVEL=INFO
    volumes:
      - qdrant_data:/qdrant/storage
      - ./health-check:/health-check:ro
    networks:
      - cortex_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  qdrant_data:
    driver: local

networks:
  cortex_network:
    driver: bridge