import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    include: ['tests/integration/**/*.test.ts'],
    exclude: ['tests/unit/**', 'tests/e2e/**', 'node_modules'],
    testTimeout: 60000, // Integration tests may take longer
    hookTimeout: 120000, // Allow time for database setup
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html', 'lcov', 'text-summary'],
      reportsDirectory: 'coverage/integration',
      exclude: [
        'tests/',
        'dist/',
        'node_modules/',
        'coverage/',
        '**/*.d.ts',
        '**/*.config.ts',
        '**/*.config.js',
        'scripts/',
        'migrations/',
        'docker/',
        '.github/',
        '.husky/',
        '.claude/',
        '.serena/',
        '.specify/',
        '*.test.ts',
        '*.spec.ts',
        'fixtures/',
        'artifacts/',
        'docs/',
      ],
      thresholds: {
        global: {
          branches: 85,
          functions: 85,
          lines: 85,
          statements: 85,
        },
        'src/services/**': {
          branches: 85,
          functions: 85,
          lines: 85,
          statements: 85,
        },
        'src/db/**': {
          branches: 85,
          functions: 85,
          lines: 85,
          statements: 85,
        },
      },
      all: true,
      clean: true,
      cleanOnRerun: true,
      enabled: true,
      watermarks: {
        statements: [85, 95],
        functions: [85, 95],
        branches: [85, 95],
        lines: [85, 95],
      },
      skipFull: false,
      allowExternal: false,
      include: ['src/**/*.ts'],
      perFile: true,
      functions: true,
      branches: true,
      statements: true,
      lines: true,
    },
    setupFiles: ['tests/setup.ts'],
    globalSetup: ['tests/global-setup.ts'],
    reporters: ['verbose', 'json'],
    outputFile: {
      json: 'test-results/integration.json',
    },
    watch: false,
    isolate: true,
    pool: 'threads',
    poolOptions: {
      threads: {
        singleThread: true,
        maxThreads: 1,
        minThreads: 1,
      },
    },
    maxConcurrency: 1,
    bail: 5,
  },
});
