# =============================================================================
# CORTEX MEMORY MCP - WSL DOCKER DEPLOYMENT
# =============================================================================
# ARCHITECTURE: Windows MCP Server + WSL2 Docker PostgreSQL
# - MCP Server runs natively on Windows (optimal performance)
# - PostgreSQL runs in WSL2 Docker container (resource efficient)
# - Connection: Windows host → WSL2 Docker → PostgreSQL
# - Memory usage: ~800MB total (vs 3-5GB for Docker Desktop)
# - Performance: 5-10ms latency (excellent for MCP workloads)
# =============================================================================

version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    container_name: cortex-postgres
    hostname: cortex-postgres
    environment:
      # PostgreSQL Configuration
      POSTGRES_DB: cortex_prod
      POSTGRES_USER: cortex
      POSTGRES_PASSWORD: cortex_pg18_secure_2025_key
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"

      # PostgreSQL Performance Tuning (WSL2 Optimized)
      POSTGRES_SHARED_PRELOAD_LIBRARIES: pgcrypto,pg_trgm
      POSTGRES_MAX_CONNECTIONS: 100
      POSTGRES_SHARED_BUFFERS: 256MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 768MB
      POSTGRES_MAINTENANCE_WORK_MEM: 64MB
      POSTGRES_CHECKPOINT_COMPLETION_TARGET: 0.9
      POSTGRES_WAL_BUFFERS: 16MB
      POSTGRES_DEFAULT_STATISTICS_TARGET: 100

      # Performance Monitoring
      PGSTATS_STATEMENTS_TIMEOUT: 30s

    ports:
      # Expose to Windows host (localhost:5433)
      - "5433:5432"

    volumes:
      # PostgreSQL Data Volume
      - cortex_data:/var/lib/postgresql/data

      # Database Schema and Extensions
      - ../migrations/001_complete_schema.sql:/docker-entrypoint-initdb.d/02-schema.sql:ro
      - ../scripts/init-extensions.sql:/docker-entrypoint-initdb.d/01-extensions.sql:ro

      # PostgreSQL Configuration (WSL2 Optimized)
      - ../config/postgresql.conf:/etc/postgresql/postgresql.conf:ro

      # Backup Volume
      - cortex_backups:/backups

    restart: unless-stopped

    # Health Checks (WSL2 Optimized)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cortex -d cortex_prod -t 5"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

    # Resource Limits (WSL2 Optimized)
    deploy:
      resources:
        limits:
          memory: 1G          # Conservative memory limit
          cpus: '1.5'        # CPU limit for WSL2
        reservations:
          memory: 512M       # Memory reservation
          cpus: '0.5'        # CPU reservation

    # WSL2 Specific Optimizations
    shm_size: 128m             # Shared memory for PostgreSQL
    read_only: false
    stdin_open: true
    tty: true

    # Networking
    networks:
      - cortex_network

    # Logging (WSL2 Optimized)
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "cortex,postgres,wsl"

    # Security
    security_opt:
      - no-new-privileges:true

    # Environment Labels
    labels:
      - "cortex.component=database"
      - "cortex.environment=wsl"
      - "cortex.version=1.0.0"
      - "deployment.type=wsl"

  # Optional: pgAdmin for Database Management (WSL2)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cortex-pgadmin-wsl
    environment:
      PGADMIN_DEFAULT_EMAIL: cortex@cortex.local
      PGADMIN_DEFAULT_PASSWORD: cortex_admin_2025
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"

    ports:
      # Expose to Windows host (localhost:8080)
      - "8080:80"

    volumes:
      - pgadmin_data:/var/lib/pgadmin

    restart: unless-stopped

    # Health Checks
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Resource Limits (Lightweight)
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'

    # Networking
    networks:
      - cortex_network

    # Labels
    labels:
      - "cortex.component=admin"
      - "cortex.environment=wsl"
      - "cortex.optional=true"

# Docker Networks
networks:
  cortex_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
    labels:
      - "cortex.network=wsl"

# Docker Volumes
volumes:
  cortex_data:
    driver: local
    labels:
      - "cortex.volume=database"
      - "cortex.environment=wsl"

  cortex_backups:
    driver: local
    labels:
      - "cortex.volume=backups"
      - "cortex.environment=wsl"

  pgadmin_data:
    driver: local
    labels:
      - "cortex.volume=admin"
      - "cortex.environment=wsl"