/**
 * Environment variable keys configuration
 * Centralizes all environment variable names with type safety and documentation
 */

export const ENV_KEYS = {
  // Core Application
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  HOST: 'HOST',
  NODE_ID: 'NODE_ID',
  SERVICE_NAME: 'SERVICE_NAME',
  DEBUG_MODE: 'DEBUG_MODE',

  // External Services
  OPENAI_API_KEY: 'OPENAI_API_KEY',
  QDRANT_URL: 'QDRANT_URL',
  QDRANT_API_KEY: 'QDRANT_API_KEY',
  QDRANT_COLLECTION_NAME: 'QDRANT_COLLECTION_NAME',
  QDRANT_TIMEOUT: 'QDRANT_TIMEOUT',
  QDRANT_MAX_CONNECTIONS: 'QDRANT_MAX_CONNECTIONS',
  QDRANT_HOST: 'QDRANT_HOST',
  QDRANT_PORT: 'QDRANT_PORT',
  QDRANT_DATABASE: 'QDRANT_DATABASE',
  QDRANT_COLLECTION_PREFIX: 'QDRANT_COLLECTION_PREFIX',

  // MCP Configuration
  MCP_API_KEY: 'MCP_API_KEY',
  MCP_TRANSPORT: 'MCP_TRANSPORT',

  // Authentication & Security
  JWT_SECRET: 'JWT_SECRET',
  JWT_EXPIRES_IN: 'JWT_EXPIRES_IN',
  JWT_REFRESH_SECRET: 'JWT_REFRESH_SECRET',
  JWT_REFRESH_EXPIRES_IN: 'JWT_REFRESH_EXPIRES_IN',
  AUTH_SECRET: 'AUTH_SECRET',
  BCRYPT_ROUNDS: 'BCRYPT_ROUNDS',
  REQUIRE_API_KEY: 'REQUIRE_API_KEY',
  CORS_ORIGIN: 'CORS_ORIGIN',
  HELMET_ENABLED: 'HELMET_ENABLED',

  // Database Configuration
  DATABASE_TYPE: 'DATABASE_TYPE',
  DATABASE_TIMEOUT: 'DATABASE_TIMEOUT',
  DB_CONNECTION_TIMEOUT: 'DB_CONNECTION_TIMEOUT',
  DB_MAX_CONNECTIONS: 'DB_MAX_CONNECTIONS',

  // Logging
  LOG_LEVEL: 'LOG_LEVEL',
  LOG_FORMAT: 'LOG_FORMAT',
  LOG_TIMESTAMP: 'LOG_TIMESTAMP',
  LOG_REQUEST_ID: 'LOG_REQUEST_ID',

  // Memory & Performance
  MEMORY_AUTO_CLEANUP: 'MEMORY_AUTO_CLEANUP',
  MEMORY_CHECK_INTERVAL: 'MEMORY_CHECK_INTERVAL',
  MEMORY_CLEANUP_RETRIES: 'MEMORY_CLEANUP_RETRIES',
  MEMORY_WARNING_THRESHOLD: 'MEMORY_WARNING_THRESHOLD',
  MEMORY_CRITICAL_THRESHOLD: 'MEMORY_CRITICAL_THRESHOLD',
  MEMORY_EMERGENCY_THRESHOLD: 'MEMORY_EMERGENCY_THRESHOLD',
  MEMORY_LOG_USAGE: 'MEMORY_LOG_USAGE',
  MEMORY_LOG_INTERVAL: 'MEMORY_LOG_INTERVAL',
  MEMORY_PROFILING: 'MEMORY_PROFILING',
  MEMORY_PROFILING_INTERVAL: 'MEMORY_PROFILING_INTERVAL',
  MEMORY_TREND_WINDOW: 'MEMORY_TREND_WINDOW',
  MAX_MEMORY_MB: 'MAX_MEMORY_MB',
  MAX_MEMORY_ITEMS: 'MAX_MEMORY_ITEMS',
  MIN_MEMORY_MB: 'MIN_MEMORY_MB',
  MAX_HEAP_SIZE_MB: 'MAX_HEAP_SIZE_MB',

  // Garbage Collection
  GC_ENABLED: 'GC_ENABLED',
  GC_TRIGGER_THRESHOLD: 'GC_TRIGGER_THRESHOLD',

  // Embedding Configuration
  EMBEDDING_BATCH_SIZE: 'EMBEDDING_BATCH_SIZE',
  EMBEDDING_CACHE_ENABLED: 'EMBEDDING_CACHE_ENABLED',
  EMBEDDING_CACHE_SIZE: 'EMBEDDING_CACHE_SIZE',
  EMBEDDING_CACHE_MEMORY_MB: 'EMBEDDING_CACHE_MEMORY_MB',
  EMBEDDING_CACHE_EVICTION: 'EMBEDDING_CACHE_EVICTION',
  EMBEDDING_MEMORY_MONITORING: 'EMBEDDING_MEMORY_MONITORING',
  EMBEDDING_MEMORY_THRESHOLD_MB: 'EMBEDDING_MEMORY_THRESHOLD_MB',
  EMBEDDING_CIRCUIT_BREAKER: 'EMBEDDING_CIRCUIT_BREAKER',
  EMBEDDING_CIRCUIT_BREAKER_TIMEOUT: 'EMBEDDING_CIRCUIT_BREAKER_TIMEOUT',

  // Vector Configuration
  VECTOR_SIZE: 'VECTOR_SIZE',
  VECTOR_DISTANCE: 'VECTOR_DISTANCE',
  SIMILARITY_THRESHOLD: 'SIMILARITY_THRESHOLD',

  // Deduplication Configuration
  DEDUPE_ENABLED: 'DEDUPE_ENABLED',
  DEDUPE_MAX_AGE_DAYS: 'DEDUPE_MAX_AGE_DAYS',
  DEDUPE_MAX_HISTORY_HOURS: 'DEDUPE_MAX_HISTORY_HOURS',
  DEDUPE_SIMILARITY_THRESHOLD: 'DEDUPE_SIMILARITY_THRESHOLD',
  DEDUPE_MERGE_STRATEGY: 'DEDUPE_MERGE_STRATEGY',
  DEDUPE_TIME_BASED: 'DEDUPE_TIME_BASED',
  DEDUPE_WINDOW_DAYS: 'DEDUPE_WINDOW_DAYS',
  DEDUPE_CROSS_SCOPE: 'DEDUPE_CROSS_SCOPE',

  // TTL Configuration
  TTL_DEFAULT_HOURS: 'TTL_DEFAULT_HOURS',

  // Health Check Configuration
  HEALTH_CHECK_INTERVAL_MS: 'HEALTH_CHECK_INTERVAL_MS',
  HEALTH_CHECK_TIMEOUT: 'HEALTH_CHECK_TIMEOUT',
  HEALTH_CHECK_TIMEOUT_MS: 'HEALTH_CHECK_TIMEOUT_MS',
  HEALTH_CHECK_RETRIES: 'HEALTH_CHECK_RETRIES',
  HEALTH_CHECK_RETRY_ATTEMPTS: 'HEALTH_CHECK_RETRY_ATTEMPTS',
  HEALTH_CHECK_RETRY_DELAY: 'HEALTH_CHECK_RETRY_DELAY',
  HEALTH_CHECK_RETRY_DELAY_MS: 'HEALTH_CHECK_RETRY_DELAY_MS',
  ENABLE_HEALTH_CHECKS: 'ENABLE_HEALTH_CHECKS',
  ENABLE_DETAILED_HEALTH_CHECKS: 'ENABLE_DETAILED_HEALTH_CHECKS',
  ENABLE_DETAILED_HEALTH_ENDPOINTS: 'ENABLE_DETAILED_HEALTH_ENDPOINTS',
  ENABLE_LIVENESS_PROBE: 'ENABLE_LIVENESS_PROBE',
  ENABLE_READINESS_PROBE: 'ENABLE_READINESS_PROBE',
  SKIP_OPTIONAL_HEALTH_CHECKS: 'SKIP_OPTIONAL_HEALTH_CHECKS',
  HEALTH_ENDPOINT_AUTH_REQUIRED: 'HEALTH_ENDPOINT_AUTH_REQUIRED',
  HEALTH_ENDPOINT_API_KEY: 'HEALTH_ENDPOINT_API_KEY',
  HEALTH_ENDPOINT_ALLOWED_IPS: 'HEALTH_ENDPOINT_ALLOWED_IPS',

  // Monitoring & Metrics
  ENABLE_METRICS_COLLECTION: 'ENABLE_METRICS_COLLECTION',
  ENABLE_METRICS_ENDPOINT: 'ENABLE_METRICS_ENDPOINT',
  ENABLE_PERFORMANCE_MONITORING: 'ENABLE_PERFORMANCE_MONITORING',
  MONITORING_HOST: 'MONITORING_HOST',
  MONITORING_PORT: 'MONITORING_PORT',
  MONITORING_INTERVAL_MS: 'MONITORING_INTERVAL_MS',
  MONITORING_ENABLE_AUTH: 'MONITORING_ENABLE_AUTH',
  MONITORING_ENABLE_CORS: 'MONITORING_ENABLE_CORS',
  METRICS_RETENTION_MS: 'METRICS_RETENTION_MS',
  ERROR_RETENTION_MS: 'ERROR_RETENTION_MS',
  MAX_ERROR_HISTORY: 'MAX_ERROR_HISTORY',
  MIN_THROUGHPUT_RPS: 'MIN_THROUGHPUT_RPS',
  MIN_UPTIME_SECONDS: 'MIN_UPTIME_SECONDS',

  // Alerting Configuration
  ENABLE_ALERTING: 'ENABLE_ALERTING',
  ALERT_ERROR_RATE_THRESHOLD: 'ALERT_ERROR_RATE_THRESHOLD',
  ALERT_RESPONSE_TIME_THRESHOLD: 'ALERT_RESPONSE_TIME_THRESHOLD',
  ALERT_MEMORY_USAGE_THRESHOLD: 'ALERT_MEMORY_USAGE_THRESHOLD',
  ALERT_CPU_USAGE_THRESHOLD: 'ALERT_CPU_USAGE_THRESHOLD',
  ALERT_DISK_USAGE_THRESHOLD: 'ALERT_DISK_USAGE_THRESHOLD',
  MAX_ERROR_RATE: 'MAX_ERROR_RATE',
  MAX_RESPONSE_TIME_MS: 'MAX_RESPONSE_TIME_MS',

  // Error Handling & Recovery
  ENABLE_ERROR_RECOVERY: 'ENABLE_ERROR_RECOVERY',
  ENABLE_ERROR_REPORTING: 'ENABLE_ERROR_REPORTING',
  ENABLE_ERROR_METRICS: 'ENABLE_ERROR_METRICS',
  MAX_RECOVERY_ATTEMPTS: 'MAX_RECOVERY_ATTEMPTS',
  RECOVERY_DELAY_MS: 'RECOVERY_DELAY_MS',

  // Validation Configuration
  ENABLE_DEEP_VALIDATIONS: 'ENABLE_DEEP_VALIDATIONS',
  VALIDATION_TIMEOUT_MS: 'VALIDATION_TIMEOUT_MS',
  VALIDATION_RETRY_ATTEMPTS: 'VALIDATION_RETRY_ATTEMPTS',
  VALIDATION_STRICT_MODE: 'VALIDATION_STRICT_MODE',
  SKIP_OPTIONAL_VALIDATIONS: 'SKIP_OPTIONAL_VALIDATIONS',

  // Security & Privacy
  ENABLE_ENCRYPTION: 'ENABLE_ENCRYPTION',
  ENABLE_COMPRESSION: 'ENABLE_COMPRESSION',
  ENABLE_PII_REDACTION: 'ENABLE_PII_REDACTION',
  ENABLE_SENSITIVE_DATA_REDACTION: 'ENABLE_SENSITIVE_DATA_REDACTION',
  ENABLE_GDPR_CONSENT: 'ENABLE_GDPR_CONSENT',
  ENABLE_SECURITY_LOGGING: 'ENABLE_SECURITY_LOGGING',
  ENABLE_ACCESSIBILITY: 'ENABLE_ACCESSIBILITY',
  ENCRYPTION_KEY: 'ENCRYPTION_KEY',
  API_KEY_LENGTH: 'API_KEY_LENGTH',

  // Rate Limiting
  RATE_LIMIT_ENABLED: 'RATE_LIMIT_ENABLED',
  RATE_LIMIT_MAX: 'RATE_LIMIT_MAX',
  RATE_LIMIT_WINDOW: 'RATE_LIMIT_WINDOW',

  // Cache Configuration
  CACHE_TTL: 'CACHE_TTL',

  // API Configuration
  API_TIMEOUT: 'API_TIMEOUT',

  // Session Management
  SESSION_TIMEOUT_HOURS: 'SESSION_TIMEOUT_HOURS',
  MAX_SESSIONS_PER_USER: 'MAX_SESSIONS_PER_USER',

  // Shutdown Configuration
  SHUTDOWN_TIMEOUT: 'SHUTDOWN_TIMEOUT',
  FORCE_SHUTDOWN_TIMEOUT: 'FORCE_SHUTDOWN_TIMEOUT',
  DRAIN_TIMEOUT: 'DRAIN_TIMEOUT',
  ENABLE_DRAIN_MODE: 'ENABLE_DRAIN_MODE',

  // Artifact Management
  ARTIFACTS_DIRECTORY: 'ARTIFACTS_DIRECTORY',
  MAX_ARTIFACTS: 'MAX_ARTIFACTS',
  ARTIFACT_RETENTION_DAYS: 'ARTIFACT_RETENTION_DAYS',
  ARTIFACT_COMPRESSION_ENABLED: 'ARTIFACT_COMPRESSION_ENABLED',
  ARTIFACT_ENCRYPTION_ENABLED: 'ARTIFACT_ENCRYPTION_ENABLED',
  ARTIFACT_SIGNING_ENABLED: 'ARTIFACT_SIGNING_ENABLED',
  ARTIFACT_VERIFICATION_REQUIRED: 'ARTIFACT_VERIFICATION_REQUIRED',
  ARTIFACT_ENCRYPTION_KEY: 'ARTIFACT_ENCRYPTION_KEY',

  // Audit & Logging
  ENABLE_AUDIT_LOGGING: 'ENABLE_AUDIT_LOGGING',

  // Data Export
  ENABLE_DATA_EXPORT: 'ENABLE_DATA_EXPORT',

  // Debug & Development
  ENABLE_DEBUG_MODE: 'ENABLE_DEBUG_MODE',

  // Dashboard Configuration
  SLO_DASHBOARD_HOST: 'SLO_DASHBOARD_HOST',
  SLO_DASHBOARD_PORT: 'SLO_DASHBOARD_PORT',
  DASHBOARD_API_KEY: 'DASHBOARD_API_KEY',

  // Token Management
  TOKEN_BLACKLIST_BACKUP_PATH: 'TOKEN_BLACKLIST_BACKUP_PATH',

  // System Requirements
  MIN_NODE_VERSION: 'MIN_NODE_VERSION',
  MIN_DISK_SPACE_GB: 'MIN_DISK_SPACE_GB',

  // Build & Deployment
  BUILD_NUMBER: 'BUILD_NUMBER',
  NODE_OPTIONS: 'NODE_OPTIONS',

  // Project Context
  CORTEX_ORG: 'CORTEX_ORG',
  CORTEX_PROJECT: 'CORTEX_PROJECT',
  CORTEX_BRANCH: 'CORTEX_BRANCH',
  CORTEX_SILENT_DEBUG: 'CORTEX_SILENT_DEBUG',
} as const;

// Environment variable value types
export type EnvironmentKey = (typeof ENV_KEYS)[keyof typeof ENV_KEYS];

// Critical environment variables that must be present for startup
export const CRITICAL_ENV_VARS = [
  ENV_KEYS.NODE_ENV,
  ENV_KEYS.OPENAI_API_KEY,
  ENV_KEYS.QDRANT_URL,
  ENV_KEYS.QDRANT_COLLECTION_NAME,
  ENV_KEYS.LOG_LEVEL,
] as const;

// Optional environment variables with defaults
export const OPTIONAL_ENV_VARS = [
  ENV_KEYS.PORT,
  ENV_KEYS.HOST,
  ENV_KEYS.DEBUG_MODE,
  ENV_KEYS.QDRANT_API_KEY,
  ENV_KEYS.QDRANT_HOST,
  ENV_KEYS.QDRANT_PORT,
  ENV_KEYS.QDRANT_DATABASE,
  ENV_KEYS.QDRANT_COLLECTION_PREFIX,
  ENV_KEYS.VECTOR_SIZE,
  ENV_KEYS.ENABLE_HEALTH_CHECKS,
  ENV_KEYS.ENABLE_METRICS_COLLECTION,
] as const;

// Helper functions
export function isCriticalEnvVar(key: string): boolean {
  const criticalVars = CRITICAL_ENV_VARS as readonly string[];
  return criticalVars.includes(key);
}

export function isOptionalEnvVar(key: string): boolean {
  const optionalVars = OPTIONAL_ENV_VARS as readonly string[];
  return optionalVars.includes(key);
}

export function getEnvVar(key: string): string | undefined {
  return process.env[key];
}

export function getEnvVarRequired(key: string): string {
  const value = process.env[key];
  if (value === undefined || value === '') {
    throw new Error(`Required environment variable ${key} is missing or empty`);
  }
  return value;
}

export function getEnvVarWithDefault(key: string, defaultValue: string): string {
  return process.env[key] ?? defaultValue;
}

export function getEnvVarAsBoolean(key: string, defaultValue = false): boolean {
  const value = process.env[key];
  if (value === undefined) return defaultValue;
  return value.toLowerCase() === 'true';
}

export function getEnvVarAsNumber(key: string, defaultValue?: number): number {
  const value = process.env[key];
  if (value === undefined) {
    if (defaultValue !== undefined) return defaultValue;
    throw new Error(`Environment variable ${key} is required to be a number`);
  }
  const parsed = Number(value);
  if (isNaN(parsed)) {
    throw new Error(`Environment variable ${key} must be a valid number, got: ${value}`);
  }
  return parsed;
}
